### ISSUE TITLE
Is Bug? BinaryHeap

### ISSUE THREAD

**Issue by 474420502** [emirpasic/gods#102]
```golang
type User struct {
	Priority int
	Args     []interface{}
	Method   func(args ...interface{}) bool
}

// Custom comparator (sort by IDs)
func byID(a, b interface{}) int {

	// Type assertion, program will panic if this is not respected
	c1 := a.(User)
	c2 := b.(User)

	switch {
	case c1.Priority > c2.Priority:
		return 1
	case c1.Priority < c2.Priority:
		return -1
	default:
		return 0
	}
}

func TestMain(t *testing.T) {
	set := binaryheap.NewWith(byID)

	set.Push(User{1, []interface{}{1.0, 2.0}, Equal})
	set.Push(User{3, []interface{}{1.0, 2.0}, Equal})
	set.Push(User{2, []interface{}{1.0, 2.0}, Equal})
	set.Push(User{2, []interface{}{3.0, 2.0}, Equal})
	set.Push(User{2, []interface{}{3.0, 2.0}, Equal})

	t.Error(set.Values()) //  [{1 [1 2] 0x51fd40} {2 [3 2] 0x51fd40} {2 [1 2] 0x51fd40} {3 [1 2] 0x51fd40} {2 [3 2] 0x51fd40}]
}
```
Priority list = 1 2 2 3 2 // ? 1 2 2 2 3?

**Comment by emirpasic** [comment]
@474420502 i think that's the expected behavior as per definition of the binary heap.

https://www.cs.cmu.edu/~adamchik/15-121/lectures/Binary%20Heaps/heaps.html

> A binary heap is a complete binary tree which satisfies the heap ordering property. The ordering can be one of two types:


> - the min-heap property: the value of each node is greater than or equal to the value of its parent, with the minimum-value element at the root.
> - the max-heap property: the value of each node is less than or equal to the value of its parent, with the maximum-value element at the root.

![](https://www.cs.cmu.edu/~adamchik/15-121/lectures/Binary%20Heaps/pix/heap.bmp)
