### ISSUE TITLE
Iterator methods panic after copy

### ISSUE THREAD

**Issue by lthibault** [emirpasic/gods#103]
Copying a `treeset.Iterator` will result in panics when `treeset.Iterator.Value()` is called.  I suspect the same holds for all `Iterate()` methods.

Because `Iterator` is stateful, I suggest returning an `*Iterator` from all `Iterate()` methods.

**Comment by emirpasic** [comment]
@lthibault excuse the late replay, could you provide a sample code that triggers this behaviour?
