### ISSUE TITLE
Method for adding sorted sequence in tree like data structures

### ISSUE THREAD

**Issue by Khadmium** [emirpasic/gods#105]
Functions like putAll(Map) in java or insertion_hint concept in c++ gives possibility to add some range of sorted values to map in more efficient way. Maybe I didn't notice something, but currently similar optimization cannot be achieved with existing interface.

**Comment by emirpasic** [comment]
That's correct, at the moment there is no PutAll() function for trees and I am not sure at the moment if we have the resources to implement that optimization. For now, doing single element insertions will have to suffice.

Generally speaking, even in Java, the only optimization usually this entails is to allocate enough memory from the start, but the elements are still usually inserted one by one. 

In case of a TreeMap, digging deep into it there is this optimization when cloning another sorted data structure to a sorted tree:
https://github.com/eagle518/jdk-source-code/blob/91b771140de051fb843af246ab826dd6ff688fe3/jdk6u21_src/j2se/src/share/altclasses/java/util/TreeMap.java#L3280
(it does save a few clock cycles for sure, but it will take some time for this to become a bottleneck in any project)
