### ISSUE TITLE
Add RemoveLeft() and RemoveRight() to all ordered trees

### ISSUE THREAD

**Issue by elecprog** [emirpasic/gods#111]
These are often used in algorithms and remove the need for two lookups (one for Left()/Right() and one for Remove()). This also makes it cleaner to use a tree as a priority queue.

**Comment by elecprog** [comment]
This is of course a partial duplicate of #28 and the approach in #98 would make sense here as the next element before removal would remain the next element after removal (as the tree is ordered).

**Comment by emirpasic** [comment]
One can always extend the structure rather than adding more and more functionality to the data structure, i.e. feature creeping, that might in the end turn this lib unusable due to too many functions
