### ISSUE TITLE
features new Data Structures

### ISSUE THREAD

**Issue by LucaPaterlini** [emirpasic/gods#112]
Could you please add 2-4 tree
and then queap.

Happy to contribute as my best, so far my obstacle is the
fact that I was not able to file a complete implementation of any 
of the two in any language or pseudolanguage

Tk in advance,
LP

**Comment by emirpasic** [comment]
@LucaPaterlini looking at [Wikipedia](https://en.wikipedia.org/wiki/2%E2%80%933%E2%80%934_tree) this looks like a B-Tree, right?

**Comment by emirpasic** [comment]
queap and other queues to come in another PR in future
