### ISSUE TITLE
linkedhashmap.Map doesn't implement the json.Marshaler/json.Unmarshaler interfaces

### ISSUE THREAD

**Issue by ekinanp** [emirpasic/gods#116]
This makes it annoying to use when testing because `json.Marshal`/`json.Unmarshal` don't work with it (especially when you mix-it in with other types like e.g. `map[string]*linkedhashmap.Map`).

**Comment by cmitchell** [comment]
There are two ways you could work around this issue. (The author did an awesome job on the actual data structures, so this is small potatoes to take care of this yourself if he doesn't get around to it)

1. You could add the following snippet that implements go's default encoding/json interface to the serialization.go for linkedhashmap and not have to change anything else in the project - t'll work "out of the box" 
`
// MarshalJSON outputs the JSON representation of map.
func (m *Map) MarshalJSON() ([]byte, error) {
	return m.ToJSON()
}

// UnmarshalJSON populates map from the input JSON representation.
func (m *Map) UnmarshalJSON(data []byte) error {
	return m.FromJSON(data)
}
`

2. If you don't want to modify this project or wait for the author to make a change, you could wrap the linkedhashmap in your own struct and have your struct implement the json interface. This allows you to continue to update this project as the author makes changes it without clobbering or having to merge your changes every time. It also allows the author to indefinitely choose to not implement it himself. 

`
type FacetConfig struct {
	Interval       int                    `json:"interval"`
	Limit          int                    `json:"limit"`
	**Buckets        *LinkedHashMap          `json:"buckets"`**
	DiscreteValMax int                    `json:"discreteValMax"`
	Intervals      map[string]*TimeConfig `json:"intervals"`
}

type LinkedHashMap struct {
	*linkedhashmap.Map
}

// MarshalJSON puts the LinkedHashMap into json
func (v LinkedHashMap) MarshalJSON() ([]byte, error) {
	return v.ToJSON()
}

// UnmarshalJSON puts the json into a LinkedHashMap
func (v *LinkedHashMap) UnmarshalJSON(data []byte) error {
	return v.FromJSON(data)
}

`
A new instance would be made as follows,
`var defaultIdentifierBuckets = &common.LinkedHashMap{linkedhashmap.New()}`

Then all of the Put(), Get() work just fine without any more wrapping, i.e. 
`defaultIdentifierBuckets.Put("0-9", "^[0-9]+")`

**Comment by emirpasic** [comment]
GoDS now implements the json interface as of #192
