### ISSUE TITLE
RBT remove doens't work if node.Left && node.Right are both nil

### ISSUE THREAD

**Issue by ngtuna** [emirpasic/gods#118]
https://github.com/emirpasic/gods/blob/master/trees/redblacktree/redblacktree.go#L136

**Comment by emirpasic** [comment]
@ngtuna true that according to the given lines of code, but when does this scenario occur. Do you have an example that leads to this state? thx4reporting

**Comment by ngtuna** [comment]
I got this issue on my application using this RBT package. I am trying to understand it. Will keep you posted on this.

**Comment by emirpasic** [comment]
@ngtuna any new input on this or something I can look into?
