### ISSUE TITLE
Remove() a element,but used Contains() that still return true, and used String() that there is no the element 

### ISSUE THREAD

**Issue by beijibeijing** [emirpasic/gods#144]
I used arraylist.List .
I Remove() a element,but used Contains() that still return true, and used String() that there is no the element.

**Comment by beijibeijing** [comment]
And I used IndexOf() that the index is not -1

**Comment by BoynChan** [comment]
Maybe you can post your code about add elements and remove elements.

**Comment by AryanAhadinia** [comment]
Actually, calling Remove(i), will remove i-th element of the list, not element with value i. For example, if you construct list [2, 3, 4, 5] and then call Remove(2). the answer will be [2, 3, 5]. It is nice to have a function RemoveValue(). I'll wirk on that.

**Comment by AryanAhadinia** [comment]
PR #149 has an implementation of RemoveValue

**Comment by beijibeijing** [comment]
I understand when calling Remove(), the i is the index, not the value.
And it happens sometimes, not every time.
When it happend,  first calling Remove(index),then I test it to call Contains(value) that still return true, to calling String() that there is no the value,to calling IndexOf(value) that the index is not -1

**Comment by AryanAhadinia** [comment]
Please write an example of when this happen. I tested several cases, but all of them worked correctly.

**Comment by emirpasic** [comment]
@beijibeijing are you accessing the list concurrently? Note that GoDS (v1) is not thread-safe by design at the moment.
