### ISSUE TITLE
Expected binaryheap to Pop int value when using NewWithIntComparator 

### ISSUE THREAD

**Issue by srikarplus** [emirpasic/gods#177]
A heap created like `heap := binaryheap.NewWithIntComparator()` is expected to `Pop` int type element. Instead the method returns an interface that needs a type assertion. Is it possible to do this type assertion by the package itself as per the Comparator used.

**Comment by emirpasic** [comment]
At the time of creating GoDS, there were no generics (as this is the case with golang 1.18). Hence, type assertions were mandatory everywhere and are take the biggest performance hit when it comes to GoDS. There is discussion and roadmap to take GoDS to generics which would avoid type assertions everywhere in GoDS v2. 

As for now, GoDS v1, works everywhere with `interface{}` types, hence the need to type assert. It's not the prettiest sight to see having to type assert everywhere, but it is not that bad either for now.

**Comment by emirpasic** [comment]
At the time of creating GoDS, there were no generics (as this is the case with golang 1.18). Hence, type assertions were mandatory everywhere and are take the biggest performance hit when it comes to GoDS. There is discussion and roadmap to take GoDS to generics which would avoid type assertions everywhere in GoDS v2. 

As for now, GoDS v1, works everywhere with `interface{}` types, hence the need to type assert. It's not the prettiest sight to see having to type assert everywhere, but it is not that bad either for now.
