### ISSUE TITLE
Question on maintenance status

### ISSUE THREAD

**Issue by achille-roussel** [emirpasic/gods#184]
Hello,

I know managing open-source software can be time consuming, and looking at the last release being in 2018, and the growing list of open issues and pull requests, it seems that maybe the popularity of this package has grown beyond the maintenance capacity of one contributor?

I'm interested in taking a dependency on the package but I am wondering whether the project is still maintained? Or whether there are known forks that have picked up the work and merged fixes for the open issues?

**Comment by emirpasic** [comment]
The project is pending a huge overhaul of resolving the PRs as well as updating to the latest version which might include support with generics. I hope that answers the question, but feel free to contribute if you have time to resolve some of the pending issues.

**Comment by achille-roussel** [comment]
I would like to contribute, but it seems a lot of the pull requests that were open in the last few months have not received feedback nor were merged in, which makes me wonder whether the effort would be effective.

Again, I understand the maintenance of these packages can be very time consuming, I'm not asking for more support, just trying to better understand the implications of taking a dependency on this project.

Thanks for the quick reply!
