### ISSUE TITLE
Add to treemap functions that search a key (similar to Floor/Ceiling) and return Iterator

### ISSUE THREAD

**Issue by vlkv** [emirpasic/gods#193]
I want to find an element in the tree for O(logN) time and then do a O(1) navigation to the next/prev from there.
Similar to c++:
- https://en.cppreference.com/w/cpp/container/map/find
- https://en.cppreference.com/w/cpp/container/map/lower_bound
- https://en.cppreference.com/w/cpp/container/map/upper_bound

**Comment by emirpasic** [comment]
@vlkv 
RedBlackTree is the foundation of the TreeMap anyways, so essentially they are the same.
The key difference is that the TreeMap is "branded" as key-value structure and avoids dealing with the internal red-black tree representation of nodes.
Do you think you can then simply use the RedBlackTree instead for your case to have this flexibility or should GoDS expose similar IteratorAt functionality?

**Comment by vlkv** [comment]
I looked closely through the public interface that both structures expose and now I see, that the major difference between them probably in that rbt exposes the Node abstraction and treemap - does not. 

> Do you think you can then simply use the RedBlackTree
Yes, sure.

> should GoDS expose similar IteratorAt functionality?
I was expected to see something like c++ std::map or Java's TreeMap and I didn't. But this is simply because of my poor knowlegde of GoDS. Honestly I don't know, this is more of a GoDS philosophy/ideology question, so it's up to you.

Thank you for your help))
