### ISSUE TITLE
some problem of contains

### ISSUE THREAD

**Issue by walkmiao** [emirpasic/gods#204]
1. Add will trigger resize,length and cap is cap value
`func (list *List) resize(cap int) {
	newElements := make([]interface{}, cap, cap)
	copy(newElements, list.elements)
	list.elements = newElements
}`
2. Contains will iterate default nil value,list.elements is the resized newElements。
`func (list *List) Contains(values ...interface{}) bool {

	for _, searchValue := range values {
		found := false
		for _, element := range list.elements {
			if element == searchValue {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}`

**Comment by emirpasic** [comment]
@walkmiao what seems to be the problem?

**Comment by walkmiao** [comment]
> @walkmiao what seems to be the problem?

if values contains a value = nil and list.elements  contains nil,but we never add nil to list.elements. 
another one, contains iterate cap(elements)-len(elements) times meaningless operation?

**Comment by emirpasic** [comment]
@walkmiao I think I see your point, I'll implement a fix for all structures that might have such scenarios

**Comment by emirpasic** [comment]
@walkmiao thanks for reporting the issue. 
This has been resolved in v1.18.1 by #205
