### ISSUE TITLE
Coverity Scan - Explicit null dereferenced

### ISSUE THREAD

**Issue by raghvendra-dixit** [emirpasic/gods#209]
File: https://github.com/emirpasic/gods/blob/master/lists/doublylinkedlist/doublylinkedlist.go
Details:
A null pointer exception will occur.
In github.​com/emirpasic/gods/lists/doublylinkedlist.​List.​Insert(int, []interface{}): Dereference of an explicit null (nil) value ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))
Screenshot:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/93790023/182482719-3eb7f3e1-f455-4641-9ac8-4887914aca01.png">

**Comment by emirpasicspread** [comment]
Logically that's impossible as far as I can see as the _beforeElement_ will be assigned a value either in https://github.com/emirpasic/gods/blob/master/lists/doublylinkedlist/doublylinkedlist.go#L263 or in https://github.com/emirpasic/gods/blob/master/lists/doublylinkedlist/doublylinkedlist.go#L268 given the list is not empty, and if the list is empty the function exits at https://github.com/emirpasic/gods/blob/master/lists/doublylinkedlist/doublylinkedlist.go#L252
