### ISSUE TITLE
I would like to know how to delete a node data while treemap loop read. I want to know where is my code wrong?

### ISSUE THREAD

**Issue by zpcodemen** [emirpasic/gods#219]
package main

    import (
	    "fmt"
	    "github.com/emirpasic/gods/maps/treemap"
	    "github.com/shopspring/decimal"
    )

    type comParam struct {
	    price decimal.Decimal
	    offset int64
    }

    func numOffsetDescComparator(a, b interface{}) int {
	    aAsserted := a.(*comParam)
	    bAsserted := b.(*comParam)
            fmt.Println("aAsserted",aAsserted.price)
	    fmt.Println("bAsserted",bAsserted.price)
	    x := aAsserted.price.Cmp(bAsserted.price)
	    if x != 0 {
		    fmt.Println("x:",-x)
		    return -x
	    }
	    y := aAsserted.offset - bAsserted.offset
	    if y == 0 {
		    fmt.Println("offset:",0)
		    return 0
	    } else if y > 0 {
		    fmt.Println("offset:",1)
		    return 1
	    } else {
		    fmt.Println("offset:",-1)
		    return -1
	    }
    }
    
    func testMapLoop(){
	    m := treemap.NewWith(numOffsetDescComparator)
	    //m:=treemap.NewWith(IntComparator)
	    gparam := comParam{
            price: decimal.NewFromInt(7),
		    offset:int64(1),
	    }
	    cparam := comParam{
            price: decimal.NewFromInt(3),
		    offset:int64(2),
	    }
	    dparam := comParam{
            price: decimal.NewFromInt(4),
		    offset:int64(3),
	    }
	    aparam := comParam{
            price: decimal.NewFromInt(1),
		    offset:int64(4),
	    }
	    bparam := comParam{
            price: decimal.NewFromInt(2),
		    offset:int64(5),
	    }
	    m.Put(&gparam, "g")
	    m.Put(&cparam, "c")
	    m.Put(&dparam, "d")
	    m.Put(&aparam, "a")
	    m.Put(&bparam, "b")
	    for itr := m.Iterator(); itr.Next(); {
                   fmt.Println(itr.Value())
	           if(itr.Value().(string)=="c"){
			    m.Remove(&cparam)
			    fmt.Println("afterdelete size:",m.Size())
		    }
	    }
    }

**Comment by ugurcsen** [comment]
Tree Map uses Red Black Tree which self-balancing tree. Tree balances itself with add and remove operations. So tree iteration should reset after deletion.

**Comment by zpcodemen** [comment]
> yeah.i got it .I noticed that such a delete operation is provided in the java package. Do I need to implement it myself?
add  like itr.Remove()

**Comment by zpcodemen** [comment]
> Tree Map uses Red Black Tree which self-balancing tree. Tree balances itself with add and remove operations. So tree iteration should reset after deletion.

**Comment by zpcodemen** [comment]
> Tree Map uses Red Black Tree which self-balancing tree. Tree balances itself with add and remove operations. So tree iteration should reset after deletion.

yeah.i got it .I noticed that such a delete operation is provided in the java package. Do I need to implement it myself?
add like itr.Remove()
