### ISSUE TITLE
Add to Go official wiki?

### ISSUE THREAD

**Issue by tasty0tomato** [emirpasic/gods#221]
GoDS might be one of the best and the most powerful Go-Data-Structures project. Although I think almost all Go programmers know GoDS, to let more know it, add it to [Go official wiki](https://github.com/golang/go/wiki/Projects) might be a good idea.

**Comment by emirpasic** [comment]
That's would be great, how do we make it there?

**Comment by tasty0tomato** [comment]
Have done that. Seems simple and everyone can edit it.
https://github.com/golang/go/wiki/Projects#collections
Maybe anothor better introduction?

**Comment by emirpasic** [comment]
Awesome, I think it is good, thanks a lot
