### ISSUE TITLE
generic upgrade request

### ISSUE THREAD

**Issue by guanguoyintao** [emirpasic/gods#222]
Because many container classes return []interface, there is still an O(n) range processing in the follow-up, but this problem can be solved through generics. Do you have any plans to upgrade? I can contribute

**Comment by ugurcsen** [comment]
This needs to be major upgrade for this project. It's hard to be compatible with older versions. I implement generics in this repo that you can use for now [https://github.com/ugurcsen/gods-generic](https://github.com/ugurcsen/gods-generic).
Can we publish this repo in this project as a sub-package?

**Comment by gedw99** [comment]
Thankyou @ugurcsen

**Comment by yangyile1990** [comment]
you really did a nice job!
我只能说：你干得漂亮。
@ugurcsen
