### ISSUE TITLE
Bulk Initialization

### ISSUE THREAD

**Issue by jjharr** [emirpasic/gods#27]
It'd be nice to have a bulk initialization convenience method for the container interface. Example use case is creating a hash or set of a heavily used static data set, like country information.

**Comment by emirpasic** [comment]
Sounds reasonable, but I'm just not sure if you need that for all container types? Most of the containers that contain only values, e.g lists, sets, have the Add function that can take multiple values. So I guess you need something similar for containers that have key-value pairs?

**Comment by emirpasic** [comment]
@jjharr friendly ping.

Does the list.Add(...) function provide what you need? I gave this some more thought for the key-value pairs and I am not sure of a clean way of bulk-initializing key-value pairs. Perhaps you have some ideas?

**Comment by jjharr** [comment]
Sorry, new baby in the house and it's kind of a life-bomb.

I actually completely missed the signature for Add (facepalm).

It seems like the Go type system would make the addition of a large [interface{}]interface{} map unreasonably awkward relative to just calling Put multiple times. So... I withdraw the feature request!
