### ISSUE TITLE
Bulk Constructors - arraylist.New(1, 2, 3, 4)

### ISSUE THREAD

**Issue by emirpasic** [emirpasic/gods#36]
Perhaps making New() functions of containers variadic to allow for optimized bulk insertions during initialization.

**Comment by Spriithy** [comment]
Or maybe create a new bulk constructor like so `arraylist.From(1, 2, 3, 4)` or `arraylist.Of`

**Comment by dsantosp12** [comment]
Is this something that will be implemented? I am looking for something to contribute to the Go community.

**Comment by emirpasic** [comment]
@dsantosp12 I am looking forward to implementing this. For lists and sets it's simple, but the other structures (maps/trees) I am unsure about how to pass those values and keep the API clean. I suppose we could start with lists/sets. I am planning on spending a day or two on all these new requests

**Comment by dsantosp12** [comment]
@emirpasic cool. I can start the lists/sets if you want and make a pull request and after that we can start looking at options for maps/trees structures.

**Comment by dsantosp12** [comment]
Will do this weekend!
