### ISSUE TITLE
Question regarding tests

### ISSUE THREAD

**Issue by cristaloleg** [emirpasic/gods#38]
Hi. I've a few questions about tests in [binaryheap_test.go](https://github.com/emirpasic/gods/blob/master/trees/binaryheap/binaryheap_test.go#L278) by example.

1. Why you disable timer at the beginning of the test and then enable it at the end?
2. You're pushing 100 elements, but then popping 100 * b.N, so pop function returns nothing. Am I missing something or this is a bug?

Thank you.

**Comment by emirpasic** [comment]
Perhaps, which is most likely, is that I did not understand the question. So excuse me if my answer misses the point.

That is a benchmark for popping, so the initialization step of populating (pushing) the heap should not  be part of the benchmark, hence the stopping of the timer.

The pop function removes the element from the heap, which bubbles down the root elements, thus changing the internal storage. The function does return a value, that is not captured in the test as you said, but that shouldn't make much difference to the benchmark, right?
