### ISSUE TITLE
How to loop a HashSet?

### ISSUE THREAD

**Issue by tooooolong** [emirpasic/gods#41]
HI, how can i loop a HashSet, i see only TreeSet has a iterator
thx!

**Comment by tooooolong** [comment]
```
ids  := set.Values()
for _, id := range(ids){
}
```
i iterate the set by this way. but if the set is too large, this approach will get a performance problem, is it?

**Comment by emirpasic** [comment]
You can't loop the HashSet. HashSet is based on Go's map whose key (thus values in the set) order is random each time. Perhaps you are fine with that random order, in which case I could enable it?
