### ISSUE TITLE
DoublyLinkedList.Insert() forgets dealing with element.prev

### ISSUE THREAD

**Issue by masknu** [emirpasic/gods#43]
In order to construct a "doubly" linked list while inserting, new element and old element's prev pointer have to get updated.
Solution:
In doublylinkedlist.go,

- Line 262, add:
-     newElement.prev = beforeElement
- Line 266, add:
-     oldNextElement.prev = beforeElement
- Line 271, add:
-     newElement.prev = beforeElement
- Line 274, add:
-     oldNextElement.prev = beforeElement

**Comment by emirpasic** [comment]
@masknu Thanks, good catch! It's been fixed now in #52
