### ISSUE TITLE
can multi children as type map?

### ISSUE THREAD

**Issue by questionpython** [emirpasic/gods#45]
hi
can multi children as type map?
example : 
>map["name":"test",5:456123123,[1:5,2:7,3:["name":"ttt","age":48]]]

**Comment by emirpasic** [comment]
@questionpython sorry, I didn't understand what you meant. Are you talking about multi-maps?

**Comment by questionpython** [comment]
example : 
```
[1,2,3,4,5,[9,8,7,[6,4,1,2],9],4,0,0]
```

**Comment by emirpasic** [comment]
@questionpython sorry, but I still don't understand your question. To me that looks like an array of elements that can either be single elements (integers) or other arrays, so I am confused about your mention of "maps".

There is nothing stopping you from doing that in GoDS as long as you type assert afterwards when fetching those elements, i.e. either it's an integer or an array. In case where the element is an array, iterate over its elements again (recursively).

Do you have a concrete example or use case of what you are trying to accomplish?
