### ISSUE TITLE
unhashable type []interface

### ISSUE THREAD

**Issue by rafw** [emirpasic/gods#57]
type HashSet struct {
	set *hashset.Set
}

func NewHashSet() *HashSet {
	var result HashSet
	result.set = hashset.New()
	return &result
}

// If call Add("abc"), it will crash and output "unhashable type []interface", why?
func (s *HashSet) Add(items ...interface{}) {
	s.set.Add(items)
}

Thank you.

**Comment by icecity96** [comment]
There is no problem with `gods`. The reason cause this problem is the way you use ...interface{}
try following:
```
func (s *HashSet) Add(items ...interface{}) {
		s.set.Add(items...)
}
```
or
```
func (s *HashSet) Add(items ...interface{}) {
	for _,item := range items {
		s.set.Add(item)
	}
}

```
