### ISSUE TITLE
better and more idiomatic support for JSON marshalling/unmarshalling

### ISSUE THREAD

**Issue by genez** [emirpasic/gods#63]
I would love to see standard MarshalJSON / UnmarshalJSON (and their streaming Encode/Decode counterparts) support.
This would allow us to persist complex structs using data structures without having to manually implement JSON reading/writing

**Comment by emirpasic** [comment]
@genez my guess is that I misunderstood the question, please correct me if so. There is JSON serialization/deserialization: https://github.com/emirpasic/gods#serialization

Let me know if that is what you are looking for?

**Comment by genez** [comment]
I am talking about **standard** json encoding/decoding facilities as provided by stdlib:
https://blog.golang.org/json-and-go

If your structs implement these two functions (MarshalJSON, UnmarshalJSON) we are able to recursively marshal struct that are embedding one of your data structures in a seamless way.

I hope it's clear enough, feel free to ask for more details.

**Comment by emirpasic** [comment]
@genez I get your point, the marshalling would be easy to implement, because the logic is already there. 

However, unmarshalling is a bit problematic, if you get a JSON array, what should it be unmarshalled to? ArrayList, LinkedList, Stack, etc.

**Comment by genez** [comment]
Go's marshal stdlib requires the actual struct instance (a pointer to) that must be of the required type.
Maybe I can try to implement one so it becomes clear.

**Comment by emirpasic** [comment]
@genez please do, just one example, e.g. for ArrayList.

You can make use of the already implemented GoDS deserialization:

```go
  list := arraylist.New()
  json := []byte(`["a","b"]`)
  err := list.FromJSON(json)
```
