### ISSUE TITLE
Iterator  support seek ?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [emirpasic/gods#66]
Any follow up plan to add "seek" function for treemap ?
like:

```
	it := m.Iterator()
	prefix :="1234"
        it.Seek(prefix)
	for it.Next() {
		...
	}
```

**Comment by emirpasic** [comment]
@zhengxiaochuan-3 sure, let's keep this issue open and see if more people vote for it.

**Comment by asdine** [comment]
Any plan for this feature?

**Comment by emirpasic** [comment]
@asdine looks like it's on the road map given the number of up votes

**Comment by emirpasic** [comment]
Related to #95

**Comment by emirpasic** [comment]
#189 brings in the two new functions that can help achieve the above, i.e. NextTo() and PrevTo()

Given the above comment on requested functionality, this can now be achieved with: 

```go
	// Seek key-value pair whose value starts with "1234"
	seek := func(key interface{}, value interface{}) bool {
		return strings.HasSuffix(value.(string), "1234")
	}

	for found := it.NextTo(seek); found; found = it.Next() {
		key, value := it.Key(), it.Value()
		...
	} 
```

For a working example refer to: https://github.com/emirpasic/gods/blob/master/examples/iteratorwithkey/iteratorwithkey.go#L71-L80

Please let me know if the above is not what was requested so I can reopen this issue.
