### ISSUE TITLE
Are all these structures thread safe?

### ISSUE THREAD

**Issue by zhaoxy2850** [emirpasic/gods#68]
Hi guys, I'm wondering whether I should use RWMutex with the structures? I'm working on a concurrent application.
Thanks very much!

**Comment by emirpasic** [comment]
@zhaoxy2850 No, they are not. Thread safety is not a concern of this project. This should be handled at a higher level, hence use of RWMutex to wrap GoDS insertion/retrieval methods is the way to go.

**Comment by zhaoxy2850** [comment]
Thanks!

**Comment by lthibault** [comment]
@emirpasic Does this these data structures are safe for concurrent *reads*? (e.g. with an iterator?)
