### ISSUE TITLE
HashMap Cannot level serialization

### ISSUE THREAD

**Issue by WangmzSee** [emirpasic/gods#70]
HashMap serialization is not hierarchically serialized for the multiplicity of value values, 
for example:
   [
        "a": [
          "b":  [:]
         ], 
        "v": ["e": 23]
   ]
At the same time, deserialization also has the same problem

**Comment by emirpasic** [comment]
@WangmzSee you essentially need to provide a specific container for serialization. GoDS can not guess that for you, in other words serializing the nested properties would need to handled manually for now.

Consider the followin:
```json
{
 "a": 1,
 "b": [1,2,3],
 "c": { "d": 4" }
}
```json

Deserializing this to HashMap works only on the first level, but the rest are either left as golang's primitives (structs and maps) or you need to define custom nested deserialziation. GoDS can not guess if "b" should be a ArrayList, LinkedList, Stack, or similary. Neither can it guess if "c" should be a HashMap. TreeMap, some type of tree, etc. 

Not sure if I have answered your question, if not, please provide more info and example code and/or ideas on how you would like the deserialziation to behave.
