### ISSUE TITLE
JSON Serialization with Integer-keyed Maps

### ISSUE THREAD

**Issue by paralin** [emirpasic/gods#71]
The following example doesn't seem to work:

```
tm1 := treemap.NewWithIntComparator()
tm1.Put(1, "x")
tm1.Put(2, "b")
tm1.Put(1, "a")

data, _ := tm1.ToJSON()

tm2 := treemap.NewWithIntComparator()
tm2.FromJSON(data) // fails
```

The serialized JSON has the integer keys in quotes - `{"1":"a","2":"b"}` which is, of course, the only possibility conforming to JSON spec. However, this is counter-intuitive. Would it not be better to store an array of key/value pairs?

**Comment by emirpasic** [comment]
I am afraid that it be even more counter-intuitive to store a map data structure as an array JSON representation.

Given the JSON specification, I frankly do not see any way to make this more intuitive. For now, as you'd expect, this should work:

```
tm2 := treemap.NewWithStringComparator()
tm2.FromJSON(data) // fails
```

**Comment by paralin** [comment]
It doesn't work. It won't parse the produced json

**Comment by emirpasic** [comment]
> It doesn't work. It won't parse the produced json

@paralin ok, i'll check it out.

**Comment by emirpasic** [comment]
@paralin 

this does work

```go
package main

import (
	"fmt"
	"github.com/emirpasic/gods/maps/treemap"
)

func main() {
	tm1 := treemap.NewWithIntComparator()
	tm1.Put(1, "x")
	tm1.Put(2, "b")
	tm1.Put(1, "a") // overwrites first key

	data, _ := tm1.ToJSON()

	tm2 := treemap.NewWithStringComparator()
	tm2.FromJSON(data) // does NOT fail

	fmt.Print(tm2.String()) // map[1:a 2:b]  CORRECT
}
```

the other issue of converting numbers to strings is explained above
