### ISSUE TITLE
GENERATE IMPLEMENTATIONS FOR GENERIC TYPES

### ISSUE THREAD

**Issue by ArnoldoR** [emirpasic/gods#77]
https://flaviocopes.com/golang-generic-generate/

it is an attractive idea

**Comment by emirpasic** [comment]
@ArnoldoR is this another code-generation tool? there have been other similar tools and i chose not to use it from the start feeling (subjectively) uneasy about this approach despite being aware that this would optimize performance and remove the need for type assertions. in other words, i am not keen on making this switch for the whole library, but would simply extend this library to have static typed generated files for all the structures. given the number of combinations of types, this would yield many many files, i.e. consider only how many types there are in golang and square that number to get combinations for key-value structures.

**Comment by emirpasic** [comment]
@bminer I concur, the performance hit is maybe not too bad nowadays. There have been a few complaints a few years ago w.r.t. type assertions, but these might have been optimized in newer versions of Golang (actually not 100% sure, would need to investigate, for now just wishful thinking). In a more complex system, based on my experience, these type assertions within this library are least likely to be the cause for the slowdown.

However, the memory might be a bit of an issue, in that case I'd suggest a custom implementation for the given problem with static types. Again, there is so much unused RAM on computers today or it's used on other bloatware, so even that might not be too much of an issue in a larger system/environment.

What did you mean by 4x the RAM? 

https://play.golang.org/p/l6HKSm_K9tS

**Comment by bminer** [comment]
I meant 4x the RAM on a 64-bit machine.  The Go playground is a 32-bit machine.  :)

**Comment by emirpasic** [comment]
writing from phone, what would be the output of that on a 64-bit?

**Comment by bminer** [comment]
`interface{}` on 64-bit is 16 bytes (two 64-bit words).
`int` on 64-bit is 8 bytes (one 64-bit word).
`int32` is always 4 bytes. You can fit 2 of them in a 64-bit word.

**Comment by emirpasic** [comment]
thanks @bminer , the interface part i wasn't sure of, otherwise makes sense.

things do get a bit more troubling with 8-bit types, e.g. bool, int8, etc.

in those cases `interface{}` will use 16 times more memory.
