### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by igrmk** [emirpasic/gods#83]
For algorithms I expect test coverage to be about 100%. However for example for red black tree current test coverage is 84.2%. Looking at more detailed output you can see some algorithm branches are untested. This is a huge factor when you choose a library on GitHub.

    go test -coverprofile=coverage.out
    go tool cover -html=coverage.out

**Comment by emirpasic** [comment]
It's hard, even impossible, to cover all test cases.  I tried to cover the edge cases in the algorithm which implicitly also tests other nested traversal paths that the test coverage tool reports as not covered.

I looked in more detail regarding what's not covered, perhaps it could go to 100%, but I honestly have no intention in covering String() function just to get that 100%. I welcome anybody to contribute through a PR
