### ISSUE TITLE
Add `set(index, value)` to List interface

### ISSUE THREAD

**Issue by bminer** [emirpasic/gods#86]
In many (most?) List implementations, a method to set a given value is often exposed.

For example, with Go slices we can do:
```go
x := make([]int, 4)
x[2] = 7 // This method is missing for ArrayList et. al.
```

Thoughts on this?  I would be willing to do a PR.

**Comment by emirpasic** [comment]
@bminer absolutely, can't believe that nobody asked for this before and i didn't add it from the start. you are welcome to do a PR

**Comment by bminer** [comment]
@emirpasic - Thanks for merging and for maintaining a really nice lib like this!  Cheers!
